name: CI/CD 
on: [pull_request, workflow_dispatch]
jobs:
  test:
    runs-on: [self-hosted, nrf24l01]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Build
        run: |
          cd test/integration
          make

      - name: Run
        run: |
          echo ${{ secrets.RUNNER_RASPBERRY3B_UBUNTU_SECRET }} | sudo -k -S ./test/integration/integration_test
          
