# This is a basic workflow to help you get started with Actions

name: documentation

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Uses Doxygen to generate the website HTML for github pages and coverage XML for later parsing
      - name: build documentation
        run: |
          sudo apt-get install doxygen
          cd docs/
          chmod +x build.sh
          ./build.sh
          
      - name: install lcov and wkhtmltopdf
        run: |
          sudo apt-get install lcov wkhtmltopdf
          
      - name: install coverxygen 
        uses: BSFishy/pip-action@v1
        with:
          packages: coverxygen imgkit
          
      - name: run coverxygen
        run: |
          mkdir ${GITHUB_WORKSPACE}/docs/coverage-html
          cd ${GITHUB_WORKSPACE}/docs/coverage-html
          python3 -m coverxygen --xml-dir ${GITHUB_WORKSPACE}/docs/xml --src-dir ${GITHUB_WORKSPACE} --output ${GITHUB_WORKSPACE}/docs/coverage-html/documentation-coverage.info
        
      - name: list documentation outputs (debugging)
        run: |
          ls ${GITHUB_WORKSPACE}/docs/
          lcov ${GITHUB_WORKSPACE}/docs/coverage-html/documentation-coverage.info
        
      - name: generate code coverage report
        run: |
          genhtml --no-prefix --no-function-coverage --no-branch-coverage ${GITHUB_WORKSPACE}/docs/coverage-html/documentation-coverage.info
          
      - name: run imgkit
        run: |
          python3 -c "import imgkit; imgkit.from_url('http://google.com', '${GITHUB_WORKSPACE}/docs/coverage.jpg')"
          
      - name: deploy documentation
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: main # The branch the action should deploy to.
          target-folder: docs/html
          folder: docs/html # The folder the action should deploy.
      
